### ISSUE TITLE
How to install the plugin

### ISSUE THREAD

**Issue by EgoTripe** [databird/npptranslate64#2]
could you describe the procedure to install this
I don't understand what I'm supposed to do with all this please thx

**Comment by VaelophisNyx** [comment]
Yeah I'm struggling to get this to work too

**Comment by alexkandy8** [comment]
1. Download the plugin and extract the plugin dll file.
2. Place the plugin.dll file under plugin folder of notepad++ installation. For me it was : C:\Program Files\Notepad++\plugins
3. Start Notepad++ as an elevated administrator and then go to: Settings -> Import -> Import plugin(s)... (import the plugin).
4. Notepad++ will show the restart message. / Sometimes it may not show it.
5. Restart the notepad++.
6. Should see new plugin under the Plugins menu. ALL DONE!!
Source: [stackoverflow](https://stackoverflow.com/questions/40015350/how-to-install-a-notepad-plugin-offline)

**Comment by alexkandy8** [comment]
If this helps you, you can close issue
